### ISSUE TITLE
Doesn't build in LLVM Clang 6.0

### ISSUE THREAD

**Issue by zappepappe** [hasse69/rar2fs#87]
LLVM Clang recently switch to building with C++14 by default and rar2fs doesn't build with the error:
dllext.cpp:47:18: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define St(x) L""x""

With an arrow pointing at the x.

**Comment by hasse69** [comment]
Thanks for the issue report. This problem was reported as early as April 2016 in issue #48.
Unfortunately one occurrence of this violation was left in the code, even in the same file, which makes we wonder what was really fixed here :( I will update and push to master ASAP.

**Comment by hasse69** [comment]
Patch pushed to master, please report back since I do not have a proper working C++14 environment to try this on.

**Comment by zappepappe** [comment]
Don't really have a proper environment either. Just tried building it in a VM and it builds fine with the patch. If you would like me to check if it works properly I will have to transfer some rar files over and check.

**Comment by hasse69** [comment]
Thanks, building should be enough. This does not really affect any functionality.
Will close the issue.
